export const REGISTER_CASE_ACTION = "REGISTER_CASE_ACTION";
export const GET_ALL_CASE_FILES_ACTION = "GET_ALL_CASE_FILES_ACTION";
export const STORE_ALL_CASE_FILES_ACTION = "STORE_ALL_CASE_FILES_ACTION";
